|not ready|
$_NOT_CLOSE_MODE?
$_DEBUG_MODE?

$nln = 10
$symb = 42
$space = 32

$size_x = 64
$size_y = 32 

$r = 5

$y = 0
$size_y times {
    $x = 0
	$size_x times {
        $xx = 0
		$x times{$x times{$xx+}}
		
		$y = 0
		$y times{$y times{$yy+}}
		
		$s = 0
		$y times {$s+}
		$x times {$s+}
		$r times {$s-}
		$s-
		$s < 0 times { printc -> $symb }
		$s < 0 times { printc -> $space }
		
		$x+
    }
	$y+
	
    printc -> $nln
}

|circle is (x-x0)^2 + (y-y0)^2 = r^2 |
