
//replace new $x with $x 0 end

e << 54
e print

def	println $a beg 
	$a print 
	10 putch
endef

//def ; beg 
//	g inc 
//endef

def $a <+ $b beg
	$a inc

	b' << $b
	b' dec

	//println b'

	if b' then
		$a <+ b' 
	endif
endef

def if $a then $z $b end $z beg
	if $a then
		$b
	endif
endef

a << 11
b << 70

if b then GG
	q << 56
	b << 0
	if b then L
		println q
	end L
end GG

//a <+ b 
println a
89 putch
